### Analise Exploratória de Dados

In [25]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


print("Bibliotecas instaladas com sucesso!!!")

Bibliotecas instaladas com sucesso!!!

In [26]:
# Carregando o arquivo da base query 1

df = pd.read_csv("data/query_01.csv")

In [27]:
# Visualizando as 5 primeiras linhas do query_01. Aqui observamos as clonuas com o Id do empregado, Primeiro Nome, Sobrenome, Nome do departamento, Pais, Nome da regional, Região e Salario

df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_TITLE,DEPARTMENT_NAME,SALARY
0,205,Shelley,Higgins,Accounting Manager,Accounting,12008
1,206,William,Gietz,Public Accountant,Accounting,8300
2,101,Neena,Yang,Administration Vice President,Executive,17000
3,102,Lex,Garcia,Administration Vice President,Executive,17000
4,100,Steven,King,President,Executive,24000

In [ ]:
# Renomeado as colunas para português

df = df.rename(
    columns={
        "EMPLOYEE_ID": "id_empregado",
        "FIRST_NAME": "nome",
        "LAST_NAME": "sobrenome",
        "JOB_TITLE": "cargo",
        "DEPARTMENT_NAME": "departamento",
        "CITY": "cidade",
        "STATE_PROVINCE": "estado",
        "COUNTRY_NAME": "pais",
        "REGION_NAME": "região",
        "SALARY": "salário",
    }
)

df.head()

,id_empregado,nome,sobrenome,cargo,departamento,salário
0,205,Shelley,Higgins,Accounting Manager,Accounting,12008
1,206,William,Gietz,Public Accountant,Accounting,8300
2,101,Neena,Yang,Administration Vice President,Executive,17000
3,102,Lex,Garcia,Administration Vice President,Executive,17000
4,100,Steven,King,President,Executive,24000

In [29]:
# Nossa base tem 58 linhas e 6 colunas.

df.shape

(58, 6)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_empregado  58 non-null     int64
 1   nome          58 non-null     object
 2   sobrenome     58 non-null     object
 3   cargo         58 non-null     object
 4   departamento  57 non-null     object
 5   salário       58 non-null     int64
dtypes: int64(2), object(4)
memory usage: 2.8+ KB

In [ ]:
# Verificando se ha valores ausentes
df.isnull().sum()

id_empregado    0
nome            0
sobrenome       0
cargo           0
departamento    1
salário         0
dtype: int64

In [32]:
# Verificando se há valores duplicados

df.duplicated().sum()

np.int64(0)

In [33]:
df[["salário"]].describe().round(2)

        salário
count     58.00
mean    9298.55
std     3189.17
min     5800.00
25%     7225.00
50%     8500.00
75%    10375.00
max    24000.00